= Produce Service API Guide
Billy Korando;
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 4
:sectlinks:
:operation-curl-request-title: Example request
:operation-http-response-title: Example response

[[overview]]
= Overview

API of Produce Service. Example of using contracts to both test an API to make sure it meets contract requirements and then generate API documentation from supplied contracts. 

Contracts can be viewed here: https://github.com/wkorando/produce-contracts[Produce API Contracts]

[[resources-tag-retrieve]]
== Find all produce

A `GET` request to retrieve all produce items

operation::ContractsTest_validate_find_all_produce[snippets='curl-request,response-body,http-request,http-response']

[[resources-tag-retrieve]]
== Find all produce whose primary name matches Path value

A `GET` request to retrieve all produce items that match primary name

operation::ContractsTest_validate_find_produce_by_name[snippets='curl-request,response-body,http-request,http-response']


[[resources-tag-retrieve]]
== Add new produce item

A `POST` to add a new produce item

operation::ContractsTest_validate_add_produce[snippets='curl-request,request-body,response-body,http-request,http-response']


[[resources-tag-retrieve]]
== Failed add new produce item

A `POST` of client attempting to add new produce item but not supplying all required fields.

operation::ContractsTest_validate_add_produce_bad_client_data[snippets='curl-request,request-body,response-body,http-request,http-response']